-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema worldbankdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `worldbankdb` ;

-- -----------------------------------------------------
-- Schema worldbankdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worldbankdb` DEFAULT CHARACTER SET utf8 ;
USE `worldbankdb` ;

-- -----------------------------------------------------
-- Table `development_indicators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `development_indicators` ;

CREATE TABLE IF NOT EXISTS `development_indicators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `access_to_electricity` DOUBLE NULL,
  `ease_of_doing_business` DOUBLE NULL,
  `educational_attaintment` DOUBLE NULL,
  `external_balance_on_good_and_services` DOUBLE NULL,
  `fertility_rate` DOUBLE NULL,
  `fossil_fuel_consumption` DOUBLE NULL,
  `GDP_growth` DOUBLE NULL,
  `GDP_per_capita` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS worldbank;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'worldbank' IDENTIFIED BY 'worldbank';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'worldbank';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `development_indicators`
-- -----------------------------------------------------
START TRANSACTION;
USE `worldbankdb`;
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (1, 'Afghanistan', 33.94, 67.71, 72.7, 40.72, 0, -38.87, 5.28, 0, 4.81, 1835.17);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (2, 'Albania', 41.15, 20.17, 100, 64.76, 7.18, -17.98, 1.67, 60.06, 2.66, 11335.2);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (3, 'Algeria', 28.03, 1.66, 99.51, 46.74, 0, -2.02, 2.98, 99.9, 2.9, 14196.74);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (4, 'Andorra', 42.55, 1.6, 100, 0, 0, 0, 1.27, 0, -0.32, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (5, 'Angola', -11.2, 17.87, 37.13, 39.34, 2.63, 11.3, 5.9, 45.93, 2.53, 6720.6);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (6, 'Argentina', -38.42, -63.62, 99.64, 57.69, 0, -0.02, 2.31, 88.81, 1.76, 20068.49);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (7, 'Armenia', 40.07, 45.04, 99.96, 71.79, 25.37, -17.43, 1.73, 73.27, 4.12, 8349.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (8, 'Aruba', 12.52, -69.97, 99.17, 0, 12.86, -11.1, 1.83, 0, 0.51, 37057.71);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (9, 'Australia', -25.27, 133.78, 100, 80.66, 29.11, -0.53, 1.85, 93.32, 2.65, 45752.55);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (10, 'Austria', 47.52, 14.55, 100, 78.77, 12.77, 3.31, 1.47, 67.24, 1.57, 48968.71);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (11, 'Azerbaijan', 40.14, 47.58, 99.98, 69.36, 15.7, 17.99, 1.95, 97.97, 1.46, 17090.7);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (12, 'Bahamas', 25.03, -77.4, 100, 58.39, 15.23, -7.03, 1.81, 0, 0.63, 30502.37);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (13, 'Bahrain', 25.93, 50.64, 100, 70.12, 14.93, 14.6, 2.09, 99.08, 3.53, 44595.44);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (14, 'Bangladesh', 23.68, 90.36, 67.34, 42.2, 7.25, -6.76, 2.18, 72.39, 6.61, 3306.11);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (15, 'Barbados', 13.19, -59.54, 100, 57.74, 0, -2.09, 1.64, 0, -0.08, 17184.03);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (16, 'Belarus', 53.71, 27.95, 100, 72.71, 0, -1.35, 1.62, 91.51, 1.87, 18172.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (17, 'Belgium', 50.5, 4.47, 100, 73.35, 31.35, 0.79, 1.75, 72.25, 1.59, 45263.16);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (18, 'Belize', 17.19, -88.5, 93.56, 55.35, 0, -2.78, 2.52, 0, 2.26, 8093.78);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (19, 'Benin', 9.31, 2.32, 38.22, 50.81, 0, -10.01, 5.14, 38.07, 4.69, 2067.57);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (20, 'Bermuda', 32.32, -64.76, 100, 0, 29.72, 17.97, 1.63, 0, -3.19, 53977.53);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (21, 'Bhutan', 27.51, 90.43, 89.83, 65.51, 4.55, -26.31, 2.11, 0, 6.15, 8341.72);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (22, 'Bolivia', -16.29, -63.59, 90.16, 50.84, 19.63, 0.51, 2.99, 83.44, 4.92, 6531.79);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (23, 'Bosnia and Herzegovina', 43.92, 17.68, 99.96, 65.01, 7.92, -19.84, 1.3, 89.52, 1.83, 11697.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (24, 'Botswana', -22.33, 24.68, 56.39, 65.84, 0, -0.38, 2.98, 67.28, 4.95, 16133.69);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (25, 'Brazil', -14.24, -51.93, 99.54, 56.83, 15.87, -0.82, 1.76, 56.35, 1.36, 15584.75);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (26, 'Brunei', 4.54, 114.73, 100, 65.54, 0, 25.79, 1.94, 100, 0.13, 80800.41);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (27, 'Bulgaria', 42.73, 25.49, 100, 71.91, 22.73, 0.65, 1.53, 72.33, 2.21, 17946.58);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (28, 'Burkina Faso', 12.24, -1.56, 19.26, 51.08, 0, -7.44, 5.57, 0, 5.73, 1670.99);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (29, 'Burundi', -3.37, 29.92, 7.39, 46.08, 0.81, -22.95, 5.84, 0, 2.26, 756.84);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (30, 'Cambodia', 12.57, 104.99, 59.56, 53.41, 0, -4.37, 2.68, 29.47, 7.05, 3333.35);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (31, 'Cameroon', 7.37, 12.35, 56.9, 44.16, 0, -4.68, 4.88, 34.06, 4.59, 3293.09);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (32, 'Canada', 56.13, -106.35, 100, 79.58, 25.75, -1.82, 1.58, 74.16, 2.21, 44226.49);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (33, 'Cayman Islands', 19.51, -80.57, 100, 0, 31.01, 0, 0, 0, 1.57, 66314.83);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (34, 'Central African Republic', 6.61, 20.94, 20.06, 33.34, 0, -16.46, 5.02, 0, -0.56, 853.27);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (35, 'Chad', 15.45, 18.73, 8.21, 36.09, 0, -5.79, 6.21, 0, 3.48, 2007.32);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (36, 'Chile', -35.68, -71.54, 99.77, 71.92, 12.6, 1.33, 1.79, 73.48, 3.6, 22252.4);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (37, 'China', 35.86, 104.2, 99.94, 68.97, 3.58, 2.38, 1.65, 88.3, 7.79, 13531.38);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (38, 'Colombia', 4.57, -74.3, 97.78, 69.27, 10.25, -3.73, 1.9, 76.33, 3.76, 13211.63);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (39, 'Comoros', -11.88, 43.87, 72.97, 46.88, 0, -18.95, 4.52, 0, 3.26, 2642.01);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (40, 'Congo DRC', -4.04, 21.76, 15.55, 34.95, 2.61, -5.6, 6.31, 3.83, 6.42, 800.31);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (41, 'Congo Republic', -0.23, 15.83, 52.34, 38.6, 0, 13.55, 4.64, 40.44, 2.66, 5663.65);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (42, 'Costa Rica', 9.75, -83.75, 99.4, 68.54, 21.57, -1.66, 1.83, 48.58, 3.75, 15115.51);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (43, 'Ivory Coast', 7.54, -5.55, 61.14, 54.66, 2.8, 5.06, 4.89, 24.39, 6.44, 3253.54);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (44, 'Croatia', 45.1, 15.2, 100, 72.54, 0, -0.77, 1.46, 72.64, 0.78, 22992.21);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (45, 'Cuba', 21.52, -77.78, 98.77, 0, 14.18, 3.57, 1.67, 87.61, 2.33, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (46, 'Cyprus', 35.13, 33.43, 100, 72.54, 25.75, -0.76, 1.37, 94.07, 1.01, 32595.7);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (47, 'Czech Republic', 49.82, 15.47, 100, 76.32, 19.42, 5.72, 1.53, 77.87, 2.28, 32771.81);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (48, 'Denmark', 56.26, 9.5, 100, 84.83, 30.68, 6.61, 1.75, 71.14, 1.78, 48524.99);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (49, 'Djibouti', 11.83, 42.59, 56.94, 52.23, 0, -25.21, 3.03, 0, 6.44, 2744.27);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (50, 'Dominica', 15.41, -61.37, 98.12, 61.1, 0, -15.29, 0, 0, -0.2, 10663.58);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (51, 'Dominican Republic', 18.74, -70.16, 98.53, 58.81, 0, -6.47, 2.43, 86.01, 5.71, 13905.09);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (52, 'Ecuador', -1.83, -78.18, 98.26, 57.49, 11.09, -1.7, 2.53, 86.76, 3.15, 10875.9);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (53, 'Egypt', 26.82, 30.8, 99.86, 56.91, 0, -8.22, 3.37, 97.44, 3.61, 10811.03);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (54, 'El Salvador', 13.79, -88.9, 94.86, 63.99, 6.62, -19.02, 2.15, 47.73, 2.49, 7234.85);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (55, 'Equatorial Guinea', 1.65, 10.27, 66.41, 40.07, 0, 22.5, 4.91, 0, -2.95, 30590.85);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (56, 'Eritrea', 15.18, 39.78, 44.05, 21.27, 0, -13.67, 4.32, 22.35, 5.44, 2012.19);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (57, 'Estonia', 58.6, 25.01, 100, 80.68, 0, 3.95, 1.59, 17.29, 3.62, 28834);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (58, 'Ethiopia', 9.15, 40.49, 33.84, 45.81, 0, -17.15, 4.74, 5.3, 9.93, 1512.62);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (59, 'Faroe Islands', 61.89, -6.91, 100, 0, 0, -3.2, 2.5, 0, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (60, 'Fiji', -16.58, 179.41, 92.89, 61.65, 5.17, 0, 2.78, 0, 3.73, 8875.44);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (61, 'Finland', 61.92, 25.75, 100, 80.08, 22.58, -0.63, 1.71, 43.97, 1.22, 42855.24);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (62, 'France', 46.23, 2.21, 100, 76.4, 17.37, -1.08, 1.98, 48.13, 1.35, 40351.57);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (63, 'French Polynesia', -17.68, -149.41, 100, 0, 0, 0, 2.02, 0, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (64, 'Gabon', -0.8, 11.61, 90.09, 44.39, 0, 24.31, 4.09, 24.13, 4.07, 17077.82);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (65, 'Gambia', 13.44, -15.31, 52.2, 47.97, 2.05, -13.02, 5.45, 0, 2.43, 2405.19);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (66, 'Georgia', 42.32, 43.36, 99.85, 81.87, 31.98, -15.23, 2.01, 70.62, 4.84, 9583.46);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (67, 'Germany', 51.17, 10.45, 100, 79.49, 24.91, 6.32, 1.47, 80.04, 2.13, 46576.21);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (68, 'Ghana', 7.95, -1.02, 72.58, 58.76, 0, -8.93, 4.11, 51.43, 6.83, 3921.98);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (69, 'Gibraltar', 36.14, -5.35, 100, 0, 0, 0, 0, 99.49, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (70, 'Greece', 39.07, 21.82, 100, 67.39, 21.75, -3, 1.36, 88, -2.4, 27206.55);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (71, 'Greenland', 71.71, -42.6, 100, 0, 10.36, -19.23, 2.07, 0, 1.32, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (72, 'Grenada', 12.26, -61.6, 91.53, 53.42, 0, -11.56, 2.16, 0, 3.07, 12675.7);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (73, 'Guam', 13.44, 144.79, 100, 0, 0, -36.91, 2.41, 0, 0.95, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (74, 'Guatemala', 15.78, -90.23, 87.98, 62.06, 3.73, -9.84, 3.13, 32.9, 3.45, 7515.93);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (75, 'Guinea', 9.95, -9.7, 29.73, 47.14, 4.43, -23.87, 5.05, 0, 6.12, 2002.29);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (76, 'Guinea-Bissau', 11.8, -15.18, 16.4, 42.51, 0, -8.5, 4.81, 0, 4.15, 1571.69);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (77, 'Guyana', 4.86, -58.93, 86.55, 55.03, 0, -14.88, 2.57, 0, 4.02, 7198.72);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (78, 'Haiti', 18.97, -72.29, 39.39, 38.35, 0, -37.42, 3.2, 18.9, 1.96, 1705.9);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (79, 'Honduras', 15.2, -86.24, 86.34, 56, 7.51, -17.75, 2.69, 51.73, 3.76, 4433.7);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (80, 'Hong Kong', 22.4, 114.11, 100, 84.91, 0, 1.94, 1.19, 93.68, 3.4, 55587.33);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (81, 'Hungary', 47.16, 19.5, 100, 72.36, 20.1, 6.66, 1.39, 71.11, 2.51, 25757.37);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (82, 'Iceland', 64.96, -19.02, 100, 78.99, 0, 6.4, 1.93, 10.79, 3, 47342.06);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (83, 'India', 20.59, 78.96, 82.32, 61.98, 9.14, -3.87, 2.38, 72.23, 7.02, 5836.66);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (84, 'Indonesia', -0.79, 113.92, 96.47, 66.28, 8.65, 0.39, 2.42, 65.83, 5.46, 10577.2);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (85, 'Iran', 32.43, 53.69, 99.66, 56.79, 16.54, 2.78, 1.97, 99.23, 2.65, 18450.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (86, 'Iraq', 33.22, 43.68, 99.34, 44.2, 0, 4.66, 4.09, 97.09, 5.65, 15889.51);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (87, 'Ireland', 53.41, -8.24, 100, 79.83, 29, 21.04, 1.92, 86.87, 6.38, 59305.58);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (88, 'Isle Of Man', 54.24, -4.55, 100, 0, 0, 0, 0, 0, 3.53, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (89, 'Israel', 31.05, 34.85, 100, 74.64, 32.46, 1.24, 3.06, 95.87, 3.76, 34571.09);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (90, 'Italy', 41.87, 12.57, 100, 72.52, 0, 1.66, 1.39, 81.63, 0.24, 37763.08);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (91, 'Jamaica', 18.11, -77.3, 95.52, 67.84, 6.81, -18.2, 2.07, 81.67, 0.68, 8508.55);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (92, 'Japan', 36.2, 138.25, 100, 77.9, 19.91, -0.41, 1.42, 91.23, 1.39, 39153.01);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (93, 'Jordan', 30.59, 36.24, 99.81, 60.79, 0, -23.63, 3.25, 97.18, 2.44, 9201.5);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (94, 'Kazakhstan', 48.02, 66.92, 99.88, 76.05, 34.08, 11.3, 2.67, 98.99, 4.47, 24103.03);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (95, 'Kenya', -0.02, 37.91, 43.57, 66.08, 0, -12.47, 3.95, 18.25, 5.9, 2883.93);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (96, 'Kiribati', -3.37, -168.73, 82.47, 46.4, 0, -76.26, 3.74, 0, 2.97, 1998.37);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (97, 'Kosovo', 42.6, 20.9, 99.88, 68.54, 0, -29.75, 2.15, 88.4, 3.48, 9416.25);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (98, 'Kuwait', 29.31, 47.48, 100, 62.48, 10.02, 26.51, 2.13, 94.63, 1.73, 75830.73);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (99, 'Kyrgyzstan', 41.2, 74.77, 99.73, 63.64, 0, -38.93, 3.13, 72.43, 4.06, 3311.54);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (100, 'Laos', 19.86, 102.5, 81.71, 49.57, 0, -16.19, 2.9, 0, 7.52, 5707.52);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (101, 'Latvia', 56.88, 24.6, 100, 80.07, 28.3, -1.82, 1.56, 60.49, 2.63, 23814.68);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (102, 'Lebanon', 33.85, 35.86, 99.95, 54.46, 0, -23.47, 2.06, 96.04, 2.11, 13245.07);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (103, 'Lesotho', -29.61, 28.23, 27.3, 57.97, 0, -48.73, 3.24, 0, 3.19, 2904.36);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (104, 'Liberia', 6.43, -9.43, 11.69, 42.06, 0, -72.57, 4.67, 0, 3.75, 1256.31);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (105, 'Libya', 26.34, 17.23, 75.64, 32.6, 0, 1.02, 2.39, 99.11, 5.72, 19339.62);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (106, 'Liechtenstein', 47.17, 9.56, 100, 64.85, 0, 0, 1.53, 0, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (107, 'Lithuania', 55.17, 23.88, 100, 80.28, 31.88, 0.37, 1.62, 71.82, 3.43, 27808.75);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (108, 'Luxembourg', 49.82, 6.13, 100, 69.42, 0, 33.5, 1.51, 85.1, 3.2, 100219.12);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (109, 'Macau', 22.2, 113.54, 100, 0, 0, 51.3, 1.17, 0, 6.58, 118859.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (110, 'Madagascar', -18.77, 46.87, 18.44, 45.16, 0, -7.25, 4.35, 0, 2.94, 1704.44);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (111, 'Malawi', -13.25, 34.3, 9.89, 56.75, 0, -9.15, 4.78, 0, 4.14, 1183.65);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (112, 'Malaysia', 4.21, 101.98, 99.81, 79.69, 11.31, 9.79, 2.08, 96.77, 5.44, 25871.4);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (113, 'Maldives', 3.2, 73.22, 99.77, 52.92, 0, 6.14, 2.06, 0, 6.21, 13408.27);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (114, 'Mali', 17.57, -4, 32.66, 52.37, 1.83, -12.52, 6.27, 0, 4.36, 2013.12);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (115, 'Malta', 35.94, 14.38, 100, 64.78, 14.35, 10.01, 1.39, 98.9, 5.66, 34326.48);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (116, 'Marshall Islands', 7.13, 171.18, 91.7, 50.85, 3.66, -49.73, 4.05, 0, 1.98, 3504.44);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (117, 'Mauritania', 21.01, -10.94, 38.42, 47.91, 0, -23.51, 4.81, 0, 3.98, 3817.21);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (118, 'Mauritius', -20.35, 57.55, 98.35, 78.64, 10.8, -11.57, 1.47, 83.11, 3.78, 19398.73);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (119, 'Mexico', 23.63, -102.55, 99.34, 72.24, 14.56, -1.56, 2.25, 90.55, 3, 17855.59);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (120, 'Micronesia', 7.43, 150.55, 72.78, 48.1, 0, -47.74, 3.27, 0, 0.67, 3372.66);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (121, 'Moldova', 47.41, 28.37, 100, 72.83, 19.65, -28.88, 1.27, 89.42, 4.28, 5893.33);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (122, 'Monaco', 43.75, 7.41, 100, 0, 0, 0, 0, 0, 4.22, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (123, 'Mongolia', 46.86, 103.85, 80.67, 66.86, 23.71, -8.79, 2.83, 93.23, 7.96, 11127.8);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (124, 'Montenegro', 42.71, 19.37, 99.96, 72.64, 0, -22.25, 1.73, 63.01, 2.75, 16273.49);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (125, 'Morocco', 31.79, -7.09, 95.83, 70.18, 0, -11.65, 2.54, 88.32, 3.57, 7479.53);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (126, 'Mozambique', -18.67, 35.53, 22.88, 53.44, 1.83, -33.99, 5.16, 9.39, 5.91, 1261.69);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (127, 'Myanmar', 21.91, 95.96, 56.47, 43.62, 0, -2.13, 2.24, 28.81, 7.2, 5021.41);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (128, 'Namibia', -22.96, 18.49, 47.69, 60.79, 0, -16.65, 3.57, 66.62, 3.77, 10223.1);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (129, 'Nauru', -0.52, 166.93, 99.16, 0, 0, -28.56, 0, 0, 14.35, 11580.24);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (130, 'Nepal', 28.39, 84.12, 80.25, 60.11, 4.62, -28.98, 2.23, 13.99, 4.66, 2475.2);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (131, 'Netherlands', 52.13, 5.29, 100, 75.88, 28.92, 9.68, 1.71, 92.17, 1.42, 49984.32);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (132, 'New Caledonia', -20.9, 165.62, 100, 0, 0, 0, 2.14, 0, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (133, 'New Zealand', -40.9, 174.89, 100, 87.02, 26.75, 1.05, 2, 60.58, 2.84, 36499.5);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (134, 'Nicaragua', 12.87, -85.21, 81.78, 54.29, 0, -17.3, 2.52, 44, 4.13, 4883.73);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (135, 'Niger', 17.61, 8.08, 16.13, 51.18, 1.02, -19.62, 7.26, 25.16, 6.21, 927.87);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (136, 'Nigeria', 9.08, 8.68, 54.31, 51.83, 0, 4.79, 5.67, 18.68, 3.81, 5681.04);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (137, 'Northern Mariana Islands', 17.33, 145.38, 100, 0, 0, -7.14, 0, 0, 4.25, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (138, 'Norway', 60.47, 8.47, 100, 82.48, 26.94, 8.28, 1.79, 59.16, 1.56, 62650.32);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (139, 'Oman', 21.51, 55.92, 100, 68.36, 12.39, 16.27, 2.91, 99.99, 3.54, 42479.05);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (140, 'Pakistan', 30.38, 69.35, 70.84, 54.45, 7.17, -7.31, 3.74, 60.06, 4.29, 4650.11);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (141, 'Palau', 7.51, 134.58, 99.13, 53.47, 0, -26.36, 2.22, 0, 2.11, 16350.87);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (142, 'Panama', 8.54, -80.78, 92.96, 65.87, 16.09, -6.01, 2.57, 81.03, 6.51, 20883.91);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (143, 'Papua New Guinea', -6.31, 143.96, 38.05, 58.77, 0, 0, 3.79, 0, 5.5, 3708.61);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (144, 'Paraguay', -23.44, -58.44, 98.57, 58.31, 11.88, 2.7, 2.57, 33.47, 4.91, 11402.93);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (145, 'Peru', -9.19, -75.02, 92.3, 67.89, 0, 1.16, 2.39, 74.92, 4.75, 12351.52);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (146, 'Philippines', 12.88, 121.77, 88.94, 60.1, 16.5, -6.03, 2.92, 60.66, 6.34, 7008.27);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (147, 'Poland', 51.92, 19.15, 100, 77.16, 23.76, 1.53, 1.35, 91.18, 3.55, 25990.43);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (148, 'Portugal', 39.4, -8.22, 100, 76.49, 16.72, -0.9, 1.31, 74.96, 0.62, 29339);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (149, 'Puerto Rico', 18.22, -66.59, 100, 69.57, 11.15, 19.92, 1.42, 0, -1.35, 36735.38);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (150, 'Qatar', 25.35, 51.18, 100, 66.66, 19.17, 30.18, 1.97, 100, 6.1, 123213.94);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (151, 'Romania', 45.94, 24.97, 100, 72.89, 6.51, -2.83, 1.56, 75.03, 2.98, 21618.27);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (152, 'Russia', 61.52, 105.32, 100, 76.29, 2.07, 7.02, 1.7, 90.79, 1.88, 24847.13);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (153, 'Rwanda', -1.94, 29.87, 19.91, 71.79, 2.84, -18.05, 4.26, 0, 7.15, 1788.98);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (154, 'Samoa', -13.76, -172.1, 97.75, 61.29, 0, -21.98, 4.12, 0, 1.27, 5857.82);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (155, 'San Marino', 43.94, 12.46, 100, 62.71, 15.76, 0, 1.26, 0, -2.66, 62697.67);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (156, 'Saudi Arabia', 23.89, 45.08, 100, 63.22, 22.96, 12.91, 2.65, 99.64, 3.81, 51587.83);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (157, 'Senegal', 14.5, -14.45, 59.27, 53.5, 2.64, -14.03, 4.91, 49.09, 5.13, 3131.03);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (158, 'Serbia', 44.02, 21.01, 99.92, 73.31, 13.15, -9.11, 1.44, 87.09, 1.66, 14908.05);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (159, 'Seychelles', -4.68, 55.49, 98.98, 60.84, 0, -11.63, 2.56, 0, 4.78, 25489.12);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (160, 'Sierra Leone', 8.46, -11.78, 16.98, 47.18, 0, -27.4, 4.75, 0, 5.03, 1495.94);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (161, 'Singapore', 1.35, 103.82, 100, 85.59, 27.63, 25.57, 1.21, 95.26, 5.18, 86068.42);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (162, 'Slovakia', 48.67, 19.7, 100, 0, 0, 2.55, 2.03, 0, 0.57, 34787);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (163, 'Slovenia', 46.15, 15, 100, 75.21, 19.17, 2.95, 1.41, 66.67, 3.1, 29091.52);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (164, 'Solomon Islands', -9.65, 160.16, 100, 75.89, 19.34, 5.64, 1.57, 63.54, 1.73, 31740.29);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (165, 'Somalia', 5.15, 46.2, 48.03, 55.04, 0, -12.21, 4.44, 0, 4.79, 2190);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (166, 'South Africa', -30.56, 22.94, 26.8, 20.12, 0, -73.9, 6.51, 0, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (167, 'South Georgia and	the South Sandwich Islands', -54.43, -36.59, 84.8, 66.14, 6.07, -0.26, 2.52, 87, 1.85, 12866.69);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (168, 'South Korea', 35.91, 127.77, 13.64, 33.09, 0, 12.24, 5.07, 71.56, -6.59, 2362.84);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (169, 'Spain', 40.46, -3.75, 100, 77.36, 21.44, 2.41, 1.33, 74.09, 0.94, 34588.85);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (170, 'Sri Lanka', 7.87, 80.77, 91.46, 60.5, 4.23, -8.7, 2.22, 47.13, 5.56, 11118.53);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (171, 'Sudan', 12.86, 30.22, 44.6, 45.64, 0, -2.29, 4.68, 31.27, 2.3, 4302.42);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (172, 'Suriname', 3.92, -56.03, 94.04, 47.23, 9.18, 14.13, 2.53, 78.43, 1.28, 15156.8);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (173, 'Sweden', 60.13, 18.64, 100, 81.99, 23, 3.86, 1.89, 30.76, 2.66, 47628.59);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (174, 'Switzerland', 46.82, 8.23, 100, 76.54, 36.28, 11.03, 1.53, 50.65, 1.96, 61314.61);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (175, 'Syria', 34.8, 39, 90.74, 41.85, 0, 0, 3.08, 98.33, 0, 0);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (176, 'Tajikistan', 38.86, 71.28, 99.28, 55.26, 11.87, -38.88, 3.61, 38.62, 7.03, 2729.33);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (177, 'Tanzania', -6.37, 34.89, 22.05, 53.26, 0, -7.75, 5.19, 13.47, 6.36, 2686.1);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (178, 'Thailand', 15.87, 100.99, 99.72, 76.56, 13.97, 7.65, 1.54, 80.17, 3.77, 15857.15);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (179, 'Timor-Leste', -8.87, 125.73, 61.5, 38.91, 0, 35.11, 4.39, 0, -0.74, 8502.44);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (180, 'Togo', 8.62, 0.82, 42.12, 52.27, 0, -16.06, 4.62, 18.87, 5.74, 1495.68);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (181, 'Tonga', -21.18, -175.2, 94.76, 61.42, 0, -45.39, 3.75, 0, 1.81, 5660.47);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (182, 'Trinidad and	Tobago', 10.69, -61.22, 100, 61.25, 5.79, 0, 1.78, 99.93, -0.16, 32007.62);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (183, 'Tunisia', 33.89, 9.54, 99.75, 66.26, 0, -9.99, 2.22, 88.22, 2.02, 11266.06);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (184, 'Turkey', 38.96, 35.24, 99.99, 72.3, 0, -4.32, 2.11, 88.84, 6.4, 23521.21);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (185, 'Turkmenistan', 38.97, 59.56, 99.99, 0, 0, -1.2, 2.9, 0, 8.99, 14726.18);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (186, 'Turks and Caicos Islands', 21.69, -71.8, 99.14, 0, 0, 0, 0, 0, 3.63, 21697.26);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (187, 'Tuvalu', -7.11, 177.65, 98.47, 0, 0, 0, 0, 0, 2.85, 3451.04);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (188, 'Uganda', 1.37, 32.29, 18.04, 58.03, 2.33, -10.74, 5.61, 0, 5.28, 1810.33);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (189, 'Ukraine', 48.38, 31.17, 99.98, 67.39, 0, -6.43, 1.47, 78.57, 0.16, 8441.75);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (190, 'United Arab	Emirates', 23.42, 53.85, 100, 79.1, 41.85, 28.24, 1.63, 90.38, 3.64, 65518.09);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (191, 'United Kingdom', 55.38, -3.44, 100, 83.4, 30.55, -1.41, 1.85, 84.25, 1.92, 41161.13);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (192, 'United States', 37.09, -95.71, 100, 83.67, 32.91, -3.13, 1.86, 83.29, 2.25, 55058.17);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (193, 'Uruguay', -32.52, -55.77, 99.61, 60.96, 9.73, -0.15, 2, 52.74, 3.41, 20479.75);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (194, 'Uzbekistan', 41.38, 64.59, 99.87, 65.6, 15.9, 0.5, 2.37, 97.91, 6.74, 6836.11);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (195, 'Vanuatu', -15.38, 166.96, 44.88, 60.59, 0, -3.56, 3.96, 0, 2.25, 2999.06);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (196, 'Venezuela', 6.42, -66.59, 99.44, 31.53, 21.73, -2.94, 2.38, 88.89, -5.87, 16652.33);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (197, 'Vietnam', 14.06, 108.28, 99.53, 66.64, 0, 0.68, 1.99, 68.91, 6.23, 5720.22);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (198, 'Yemen', 15.55, 48.52, 71.74, 32.67, 0, 0, 4.27, 98.37, -4.1, 3531.42);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (199, 'Zambia', -13.13, 27.85, 29.78, 63.52, 0, -0.27, 5.07, 9.39, 5.23, 3802.5);
INSERT INTO `development_indicators` (`id`, `country`, `latitude`, `longitude`, `access_to_electricity`, `ease_of_doing_business`, `educational_attaintment`, `external_balance_on_good_and_services`, `fertility_rate`, `fossil_fuel_consumption`, `GDP_growth`, `GDP_per_capita`) VALUES (200, 'Zimbabwe', -19.02, 29.15, 38.21, 49.83, 3.33, -15.3, 3.95, 27.83, 7.59, 2560.7);

COMMIT;

